name: studious_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5
  firebase_core: ^2.3.0
  google_sign_in: ^5.4.2
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  google_fonts: ^3.0.1
  firebase_storage: ^11.0.6
  cached_network_image: ^3.2.1
  flutter_zoom_drawer: ^2.1.2
  url_launcher: ^6.0.18
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/DB/papers/
    - assets/icons/
  

  
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
  
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 