// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOb48pVh3w5KaYAhwb8wk_a5AMNhP3UiM',
    appId: '1:509772241177:web:795468317011009aea4d88',
    messagingSenderId: '509772241177',
    projectId: 'studiousapp-b71d7',
    authDomain: 'studiousapp-b71d7.firebaseapp.com',
    storageBucket: 'studiousapp-b71d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbLJyWbmII7HUUUSPUPXwkVzqdMQyQu48',
    appId: '1:509772241177:android:9ef64aa7bb1ad930ea4d88',
    messagingSenderId: '509772241177',
    projectId: 'studiousapp-b71d7',
    storageBucket: 'studiousapp-b71d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYG4vrXdy8O2lDacQZ_9DcmI8eZH2Dtw',
    appId: '1:509772241177:ios:c587d5ba474a6be1ea4d88',
    messagingSenderId: '509772241177',
    projectId: 'studiousapp-b71d7',
    storageBucket: 'studiousapp-b71d7.appspot.com',
    androidClientId: '509772241177-u4qdej026grkvk22flcso44r05lm2p06.apps.googleusercontent.com',
    iosClientId: '509772241177-1hqduap6f2vfvb2bd7ituthp2ohl9a3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.studiousApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYG4vrXdy8O2lDacQZ_9DcmI8eZH2Dtw',
    appId: '1:509772241177:ios:c587d5ba474a6be1ea4d88',
    messagingSenderId: '509772241177',
    projectId: 'studiousapp-b71d7',
    storageBucket: 'studiousapp-b71d7.appspot.com',
    androidClientId: '509772241177-u4qdej026grkvk22flcso44r05lm2p06.apps.googleusercontent.com',
    iosClientId: '509772241177-1hqduap6f2vfvb2bd7ituthp2ohl9a3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.studiousApp',
  );
}
